### ISSUE TITLE
Handoff API?

### ISSUE THREAD

**Issue by coffeesam** [leecrossley/cordova-plugin-apple-watch#19]
Thank you for developing this plugin for the Cordova developer community.
May I know if this plugin supports or will support the Handoff API as mentioned in the link below?

https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/Handoff/HandoffFundamentals/HandoffFundamentals.html#//apple_ref/doc/uid/TP40014338

Cheers

**Comment by leecrossley** [comment]
Hi @coffeesam,

I've had a think about this and I'm not sure what the benefits would be. Perhaps if you let me know how you want to use the plugin I can help provide the best approach and implement something new if necessary.

**Comment by leecrossley** [comment]
Closing for now due to inactivity

**Comment by ostatnicky** [comment]
@leecrossley: Benefit is to continue your activity on your iPhone. Because in watchOS you're not able to open the iOS app directly. 

An example can be you have a watch app with some graphs and you want to open the graph detail in the iOS app. The best way is to use Handoff. You just swipe up the icon on your locked iPhone and you see the graph detail.
