### ISSUE TITLE
Can the userDefaults be updated by the watch and read by the phone?

### ISSUE THREAD

**Issue by etiennea** [leecrossley/cordova-plugin-apple-watch#20]
If so an example would be awesome!

**Comment by leecrossley** [comment]
sure, you can set in your WatchKit extension in the regular way: 

``` swift
NSUserDefaults.standardUserDefaults().setObject("myValue", forKey: "myKey")
```

Reading NSUserDefaults from Cordova would require a change to the plugin. Do you need it? If so I'll build it for you.

**Comment by etiennea** [comment]
Yes, I could use that.
Just a simple method to expose NSUserDefaults to the javascript.

Thanks so much Lee!

**Comment by leecrossley** [comment]
Hopefully this does the trick @etiennea - I've given it a quick test and published to npm.

**Comment by msrameshp** [comment]
Hi Leecrossley,

I am having an issue "Use of unresolved identifier MMWormhole" when I am trying to run the following code;

let wormhole = MMWormhole(applicationGroupIdentifier: "group.dtz.au", optionalDirectory: nil);

 Is this because the iWatch code is in swift and the library is in Objective-c ?. do I need like a bridging header to resolve this ?.

Please advice.
