### ISSUE TITLE
MMWormholeTransiting.h file not found

### ISSUE THREAD

**Issue by rsrbk** [leecrossley/cordova-plugin-apple-watch#30]
After installing your plugin to my cordova project i'm getting this error.
<img width="766" alt="screen shot 2015-10-24 at 11 18 15 pm" src="https://cloud.githubusercontent.com/assets/9006070/10712526/a38f145c-7aa5-11e5-8174-77f3c4fb29da.png">

**Comment by RichardLewin87** [comment]
I've got the same problem as russer.

**Comment by beatgrabe** [comment]
Me too! Any suggestions to solve the issue?

**Comment by RichardLewin87** [comment]
I've manually downloaded the whole thing and adjusted the plugin.xml file to bring in all the other header and code files. But this doesn't feel right even though I can now use the plugin so far as calling the sendMessage function. However, I cant get this to be received on the watch side (though I am only just starting my research into all of this so this might be my lack of knowledge rather than the plugin).

UPDATE:

(Still not sure if this is correct in terms of a fix).

I have now got it working by:
1. Removing all files but the "AppleWatch" header and code file from the plugin installation.
2. Adding the "MMWormhole" library (https://github.com/mutualmobile/MMWormhole) to the project and sharing it between the main app target and Watch extension target.
3. Pasting the following into my "InterfaceController.m" file (created by adding the Watch extension):

#import "MMWormhole.h"
#import "MMWormholeSession.h"

....

@property (nonatomic, strong) MMWormhole\* wormhole;
@property (nonatomic, strong) MMWormholeSession *watchConnectivityListeningWormhole;

....

self.watchConnectivityListeningWormhole = [MMWormholeSession sharedListeningSession];

[self.watchConnectivityListeningWormhole activateSessionListening];

self.wormhole = [[MMWormhole alloc] initWithApplicationGroupIdentifier:(GroupId) optionalDirectory:nil];

[self.watchConnectivityListeningWormhole listenForMessageWithIdentifier:@"testQueue" listener:^(id  _Nullable messageObject) {
        [self.label setText:@"Hello World"];
}];

**Comment by beatgrabe** [comment]
Hey!

I also added the missing references in the plugin.xml as i fixed in my pull request [#32](https://github.com/leecrossley/cordova-plugin-apple-watch/pull/32). Afterwards i still had to add the WatchConnectivity Library to my project! This issue was posted here as well [#31](https://github.com/leecrossley/cordova-plugin-apple-watch/issues/31)

**Comment by RichardLewin87** [comment]
Yep, had to add the WatchConnectivity Library too.
