### ISSUE TITLE
iOS 9.1 Crash under iPad and iPhone 4S

### ISSUE THREAD

**Issue by Mojo90** [leecrossley/cordova-plugin-apple-watch#33]
Just to let you know what I recently discovered.
Don't know yet why exactly App is completely crashing on this devices but thats a fact. if you use plugin on iOS 9.1 with iPad and iPhone 4S (which to my current knowledge are not compatible with Apple Watch) through:

```
applewatch.sendMessage(watchArray, "Queue", 
        function (){

        },
        function (error){
            console.log("error send: " + error);
        }
    );
```

than the App will crash in MMWormholeSessionContextTransiting.m on Line 70 ([self.session updateApplicationContext:currentContext error:nil];) with a:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WCSession updateApplicationContext:error:]: applicationContext cannot be nil.'
```

So what I did. I prevent execution of sending a Message with this code.
Just a workaround till now but to ensure a running app on all iOS devices:

```
var deviceType = (navigator.userAgent.match(/iPad/i))  == "iPad" ? "iPad" : (navigator.userAgent.match(/iPhone/i))  == "iPhone" ? "iPhone" : (navigator.userAgent.match(/Android/i)) == "Android" ? "Android" : (navigator.userAgent.match(/BlackBerry/i)) == "BlackBerry" ? "BlackBerry" : "null";
var deviceModel = device.model;

//don't send apple watch to iPad and iPhone 4S
if(deviceType != "iPad" && deviceModel != "iPhone4,1"){
    handleAppleWatch(watchArray, appleWatchImg);
}
```

Maybe somebody can support here from where the crash comes exactly or why App Context is nil there.

**Comment by beatgrabe** [comment]
FYI, I'm using:

```
var platform = $cordovaDevice.getPlatform();
var version  = parseFloat( $cordovaDevice.getVersion() );

if( platform === "iOS" && version >= 8.2 ) {
    applewatch.init();
    applewatch.doSomethingElse();
}
```

My approach is likely better than nesting multiple ternary operators...IMO

But as I'm looking through your code, i problably still have to catch iPad device as well ;-)

I assume that the applicationContext is going to be nil, because the WCSession cannot be established (by looking through the MMWormholeSessionContextTransiting.m code). But i think it would be better to use Xcode debugging to get the right information.

**Comment by Mojo90** [comment]
yep you should catch iPad AND iPhone 4S as well ;) just try it out...
That was just quick and dirty from me...
What I do not understand till now: why this just appeared with iOS 9.1. On 9.0.X and below this does not happen....

**Comment by beatgrabe** [comment]
Did you migrate to WatchOS 2? Because then you are using WatchConnectivity.Framework (WCSession). I think, this was not the case before. [Link to Apple](https://developer.apple.com/library/prerelease/watchos/documentation/General/Conceptual/AppleWatch2TransitionGuide/UpdatetheAppCode.html#//apple_ref/doc/uid/TP40015234-CH6-SW4)

**Comment by Mojo90** [comment]
No I didn't because I never used watchOS 1 before ;)
