### ISSUE TITLE
Getting error while setting up MMWormhole framework

### ISSUE THREAD

**Issue by vagishmm** [leecrossley/cordova-plugin-apple-watch#41]
Hi Lee,

I followed these steps to setup Cordova Plugin apple watch
1. Created sample cordova project. 
2. Added ios platform.
3. Then added iwatch target
3. Added this plugin via Command prompt
       cordova plugin add cordova-plugin-apple-watch
4. Enabled App group for both ios app and watch app
5. Initiated using 
    applewatch.init(function (appGroupId) {
    applewatch.sendMessage("test", "myqueue");
     }, function (err) {
    // an error occurred
    },
"group.com.yourcompany");
1. try to import MMWormhole in watch extension. But i am getting an error "No such module MMwormhole"

I tried to install MMwormhole via cocopods, still getting same error

In podfile i enterd this code

platform :ios, '8.2'
target 'MyApp' do
    pod 'MMWormhole'
end
target 'MyApp WatchKit Extension' do
    pod 'MMWormhole'
end

and also i tried this podfile in separate project
pod 'MMWormhole', '~> 2.0.0'

Please help me i don't know where did i missed it

**Comment by partclay** [comment]
I had a lot of trouble adding MMWormhole via CocoaPods. 

Then I realized it wasn't necessary because the Obj-C source for MMWormhole was included with the Apple Watch Cordova Plugin, so I added that to the Watch Extension build target.

Select each MMWormhole*.m file in the "Plugins" directory within your Xcode project, then in the file inspector check the target membership for the files to include your watch extension build target.

If your watch extension is written in Swift you will also need to update your Bridging-Header.h in the "Other Sources" folder to import the MMWormhole.h file, eg:
#import "MMWormhole.h"

That should get rid of the "No such module MMwormhole" error for you.

**Comment by jingkecn** [comment]
@partclay but that would cause the 'Cordova/CDV.h' file not found error

**Comment by partclay** [comment]
I ran into that too. 

Just comment out the Cordova/CDV.h include in the Bridging-Header.h file. The Apple Watch Extension doesn't include (and doesn't need) the Cordova library, so it doesn't need that header include.
